name: polymer
version: 0.17.0-dev
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: >
  Polymer.dart is a new type of library for the web, built on top of Web
  Components, and designed to leverage the evolving web platform on modern
  browsers.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  browser: '>=0.10.0 <0.11.0'
  html: '>=0.12.0 <0.13.0'
  initialize: '>=0.5.1+3 <0.7.0'
  logging: '>=0.9.2 <0.12.0'
  polymer_interop: '>=0.2.0 <0.3.0'
  smoke: '>=0.3.4 <0.4.0'
  test: '^0.12.3'
  web_components: '>=0.11.3 <0.13.0'
  reflectable:
    path: ../reflectable/reflectable
transformers:
- web_components
- test/pub_serve:
    $include: test/**_test{.*,}.dart
- reflectable:
    entry_points:
      - test/src/common/js_proxy_test.dart

dependency_overrides:
  polymer_interop:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/polymer_interop.git
environment:
  sdk: '>=1.4.0 <2.0.0'
